# Generated by Django 5.0.6 on 2024-10-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_name', models.CharField(max_length=50)),
                ('Album_release_date', models.DateField()),
                ('Ratings', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='3', max_length=10)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musician.musicianmodel')),
            ],
        ),
    ]
